# Generated by Django 4.1.7 on 2023-03-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-published_at']},
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title', 'description'], name='api_videos__title_aa04d6_idx'),
        ),
    ]
