# Generated by Django 4.1.7 on 2023-03-08 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_videos', '0002_alter_video_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='YouTubeVideo',
        ),
        migrations.RenameIndex(
            model_name='youtubevideo',
            new_name='api_videos__title_59c0d2_idx',
            old_name='api_videos__title_aa04d6_idx',
        ),
    ]
